version: "3"

services:
  app:
    image: elective-portal:testing
    restart: always
    # scale: 5
    build: .
    ports:
      # - "80-84:8080"
      - "80:8080"
    environment:
      MYSQL_HOST: dbNode
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: admin_password
      MYSQL_PORT: 3306
      MYSQL_DATABASE: elective_portal
    volumes:
      - C:\Users\sutha\Desktop\uploads:/app/Elective_Portal_Uploads

  dbNode:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=elective_portal
      - MYSQL_ROOT_PASSWORD=admin_password
