version: "3"

services:
  appNode:
    image: elective-portal
    # image: elective-portal:initial
    restart: always
    # scale: 5
    build: .
    ports:
      # - "80-84:8080"
      - "80:8080"
    environment:
      MYSQL_HOST: dbNode
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: admin_password
      MYSQL_PORT: 3306
      MYSQL_DATABASE: elective_portal

  dbNode:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=elective_portal
      - MYSQL_ROOT_PASSWORD=admin_password
